[project]
name = "bugpipe"
version = "3.0.2"
description = "Unofficial Python client for Buganizer; the Google Issue Tracking system"
readme = "README.md"
license = "MIT"
requires-python = ">=3.13"
authors = [
    { name = "Ritchie Mwewa", email = "rly0nheart@duck.com" },
]
keywords = [
    "buganizer",
    "google-issue-tracker",
    "issue-tracker",
    "bug-tracker",
    "bug-bounty",
    "vulnerability",
    "security",
    "chromium",
    "cve",
    "vrp",
    "google",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Bug Tracking",
    "Framework :: AsyncIO",
]
dependencies = [
    "httpx>=0.28.1",
    "rich>=14.3.3"
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "black[jupyter]>=26.1.0",
    "myst-parser>=5.1.0",
    "sphinx>=9.1.0",
    "sphinx-copybutton>=0.5.2",
    "sphinx-rtd-theme>=3.1.0",
]

[project.urls]
Changelog = "https://github.com/rly0nheart/bugpipe/blob/master/CHANGELOG.md"
Documentation = "https://bugpipe.readthedocs.io"
Repository = "https://github.com/rly0nheart/bugpipe"

[project.scripts]
bugpipe = "bugpipe.cli:start"

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

[tool.ruff.lint.isort]
combine-as-imports = true
